[package]
name = "untitled_lich_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy_asset_loader = "0.9"
alea = "0.2"
heron = { version = "2.0.1", features = ["2d"] }
